### ISSUE TITLE
Add documentation on how to use generator

### ISSUE THREAD

**Issue by BorntraegerMarc** [hydraslay/ng2-polymer-static-gen#1]
Would be cool too see a little bit more specific doc on how to use it :)

**Comment by tomzi8** [comment]
Yeah everybody would be grateful :)

**Comment by hydraslay** [comment]
Added detail step of generate and use the static directives.

@BorntraegerMarc @tomaszcysewski

**Comment by BorntraegerMarc** [comment]
Thank you very much @hydraslay

But I ment more on how to actually generate a new directive based on an web component. Not how to include them :)

**Comment by hydraslay** [comment]
@BorntraegerMarc  
The step 2 ~ 5 is how to generate a directive.
But it can not generate directive based on any web component. Just Polymer.
The mechanism (in [polymer-directive-generator.ts](https://github.com/hydraslay/ng2-polymer-static-gen/blob/master/src/app/polymer-directive-generator.ts) )is to execute the "PolymerElement(paper-xxx)"  just like you use the polymer component before. and save the output into a static file , and use it in webpack.


The step 6 is how to include them.
Just like a sample like [this](https://github.com/hydraslay/ng2-polymer-static) (see the [app.module.ts](https://github.com/hydraslay/ng2-polymer-static/blob/master/src/app/app.module.ts))

About [howto use the polymer component](https://github.com/vaadin/angular2-polymer)
About [howto use component in angular-cli(webpack)](https://github.com/angular/angular-cli)

**Comment by BorntraegerMarc** [comment]
Cool, thank you very much :) Do you see any possibility to create a generator for any web component?

**Comment by hydraslay** [comment]
@BorntraegerMarc 
Theoretically doable.

The generator in this project is about two things. Polymer and Webpack.
While building, Webpack won't accept a dynamic definition of component, which is the way polymer does.
So we make a generator to generate the static file to build in webpack.

If there is another component dynamically defined, and happened to be build by webpack.
Find that dynamical definition ( the implementation of js/ts) and make a new generator for that component.
Of course statically defined component don't need a generator.

But another question is , is a generator a best way or worth to be done? 
just like somebody commented in original issue, [here](https://github.com/vaadin/angular2-polymer/issues/86#issuecomment-255483077) and [here](https://github.com/vaadin/angular2-polymer/issues/86#issuecomment-255515772).
