### ISSUE TITLE
AoT support?

### ISSUE THREAD

**Issue by BorntraegerMarc** [hydraslay/ng2-polymer-static-gen#2]
When using the paper-input-directive from here: https://github.com/hydraslay/ng2-polymer-static and build the project with AoT, then I get the following error:
```
ERROR in Cannot determine the module for class PaperInputReloadConfigurationDirective in D:/projects/test-angular/src/app/paper-input-directives.ts!

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\projects\test-angular\src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

Is Ahead of Time compilation supported with these directives?

**Comment by hydraslay** [comment]
@BorntraegerMarc 
1. did you use the directive file in another project? If you use , you should define the module as the project 'ng2-polymer-static' did.

2. I don't know why the ngfactory will not be resolved, but I found someone's error was similar to yours [https://github.com/angular/angular-cli/issues/4551](https://github.com/angular/angular-cli/issues/4551) . Hope it help.

**Comment by BorntraegerMarc** [comment]
@hydraslay so you got it to work for AoT?

**Comment by hydraslay** [comment]
@BorntraegerMarc 
Actually I just realized what did you mean of 'AoT', as I may know not much than you.
No, this project dose not support AoT.
The Polymer itself has not be AoT compiled.

I just build this project with `ng build` but I got same error when `ng build --aot`.

This project was only made for solve the `lambda expression while importing polymer was not supported by webpack` problem.

**Comment by BorntraegerMarc** [comment]
Thanks for the answer

**Comment by hydraslay** [comment]
@BorntraegerMarc  Yes , AOT is available now :)

check the [repository](https://github.com/hydraslay/ng2-polymer-static) if you still be interested in it.
